title: The Evershine Origin Story
author: Aaron Ray
email: aray@evershine.io
description: 
 Come for the crypto greed. Stay for the Web3 revolution. A blog enabling power to the people.

# social links
twitter_username: redbaron1200s
github_username:  Kandy22
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal